import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://www.twtaxcalc.com";
  // Use a fixed date per deploy rather than new Date() on every request
  const lastDeploy = new Date("2026-04-09T12:00:00Z");

  return [
    {
      url: base,
      lastModified: lastDeploy,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${base}/tax-calculator`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/mortgage`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/overtime-calculator`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/severance-calculator`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/salary-calculator`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/bonus-calculator`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/pension-calculator`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/basic-living-deduction`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/labor-insurance-rates`,
      lastModified: lastDeploy,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/income-tax-brackets`,
      lastModified: new Date("2026-03-30T08:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/dependent-deduction`,
      lastModified: new Date("2026-03-30T18:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/freelancer-tax-guide`,
      lastModified: new Date("2026-03-30T22:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/supplement-premium`,
      lastModified: new Date("2026-03-30T23:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/salary-vs-freelancer`,
      lastModified: new Date("2026-03-31T00:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/tax-filing-guide`,
      lastModified: new Date("2026-03-30T18:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/dividend-tax`,
      lastModified: new Date("2026-03-30T10:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/margin-ratio`,
      lastModified: new Date("2026-03-30T12:00:00Z"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/liquidation-sim`,
      lastModified: new Date("2026-03-30T12:00:00Z"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/mortgage-full-cost`,
      lastModified: new Date("2026-03-30T14:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/buy-vs-rent`,
      lastModified: new Date("2026-03-30T16:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/real-estate-tax`,
      lastModified: new Date("2026-03-30T18:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/inheritance-tax`,
      lastModified: new Date("2026-03-30T20:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/gift-tax`,
      lastModified: new Date("2026-03-30T22:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/house-tax`,
      lastModified: new Date("2026-03-30T23:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/labor-retirement`,
      lastModified: new Date("2026-03-30T23:30:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/deduction-compare`,
      lastModified: new Date("2026-03-30T23:45:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/preschool-deduction`,
      lastModified: new Date("2026-03-30T23:55:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/foreign-income-tax`,
      lastModified: new Date("2026-03-30T23:58:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/tax-refund`,
      lastModified: new Date("2026-03-30T23:59:00Z"),
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/tax-checklist-2026`,
      lastModified: new Date("2026-03-30T23:59:30Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tax-mistakes-2026`,
      lastModified: new Date("2026-03-30T23:59:55Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/expense-deduction-compare`,
      lastModified: new Date("2026-03-30T23:59:58Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/stock-tax-2026`,
      lastModified: new Date("2026-03-31T08:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/amt-calculator`,
      lastModified: new Date("2026-03-31T10:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/joint-filing`,
      lastModified: new Date("2026-03-31T12:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/income-tax-guide-2026`,
      lastModified: new Date("2026-03-31T14:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/side-income-tax`,
      lastModified: new Date("2026-03-31T16:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tax-strategy-2026`,
      lastModified: new Date("2026-04-01T08:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tax-filing-steps`,
      lastModified: new Date("2026-04-01T12:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/retirement-planning`,
      lastModified: new Date("2026-04-01T12:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tax-refund-timeline`,
      lastModified: new Date("2026-04-01T14:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/day-trading-tax`,
      lastModified: new Date("2026-04-01T16:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/ira-vs-labor-retirement`,
      lastModified: new Date("2026-04-03T10:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/legal-tax-savings-2026`,
      lastModified: new Date("2026-04-08T10:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/rental-income-tax-2026`,
      lastModified: new Date("2026-04-08T12:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/etax-guide-2026`,
      lastModified: new Date("2026-04-09T02:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/job-change-tax-2026`,
      lastModified: new Date("2026-04-09T12:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/freelance-to-employee-2026`,
      lastModified: new Date("2026-04-09T14:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/rent-deduction-2026`,
      lastModified: new Date("2026-04-09T16:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/donation-deduction-2026`,
      lastModified: new Date("2026-04-09T18:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/savings-deduction-2026`,
      lastModified: new Date("2026-04-09T20:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/salary-deduction-2026`,
      lastModified: new Date("2026-04-09T20:30:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/disability-deduction-2026`,
      lastModified: new Date("2026-04-09T22:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/ltc-deduction-2026`,
      lastModified: new Date("2026-04-09T22:30:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tuition-deduction-2026`,
      lastModified: new Date("2026-04-16T10:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/insurance-deduction-2026`,
      lastModified: new Date("2026-04-16T12:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/mortgage-interest-deduction-2026`,
      lastModified: new Date("2026-04-16T12:30:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/medical-deduction-2026`,
      lastModified: new Date("2026-04-17T10:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/disaster-deduction-2026`,
      lastModified: new Date("2026-04-17T14:00:00Z"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
  ];
}
