import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://www.twtaxcalc.com";
  // 2026-10-03：全站首次正式上線。先前 production 一直停留在 2026-03 的 4 頁舊版，
  // 這 65 個網址（含 5 個信任頁）對 Google 而言都是首次公開的新內容，
  // 因此統一標示這個日期；之後個別頁面有更新再改成各自的日期。
  const siteUpdate = new Date("2026-10-03T00:00:00Z");

  return [
    {
      url: base,
      lastModified: siteUpdate,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${base}/tax-calculator`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/mortgage`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/overtime-calculator`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/severance-calculator`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/salary-calculator`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/bonus-calculator`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/pension-calculator`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/basic-living-deduction`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/labor-insurance-rates`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/income-tax-brackets`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/dependent-deduction`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/freelancer-tax-guide`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/supplement-premium`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/salary-vs-freelancer`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/tax-filing-guide`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/dividend-tax`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/margin-ratio`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/liquidation-sim`,
      lastModified: siteUpdate,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/mortgage-full-cost`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/buy-vs-rent`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/real-estate-tax`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/inheritance-tax`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/gift-tax`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/house-tax`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/labor-retirement`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/deduction-compare`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/preschool-deduction`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/foreign-income-tax`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/tax-refund`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 0.9,
    },
    {
      url: `${base}/tax-checklist-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tax-mistakes-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/expense-deduction-compare`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/stock-tax-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/amt-calculator`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/joint-filing`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/income-tax-guide-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/side-income-tax`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tax-strategy-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tax-filing-steps`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/retirement-planning`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tax-refund-timeline`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/day-trading-tax`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/ira-vs-labor-retirement`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/legal-tax-savings-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/rental-income-tax-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/etax-guide-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/job-change-tax-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/freelance-to-employee-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/rent-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/donation-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/savings-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/salary-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/disability-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/ltc-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/tuition-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/insurance-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/mortgage-interest-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/medical-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/disaster-deduction-2026`,
      lastModified: siteUpdate,
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: `${base}/about`,
      lastModified: new Date("2026-10-03T00:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${base}/contact`,
      lastModified: new Date("2026-10-03T00:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${base}/privacy`,
      lastModified: new Date("2026-10-03T00:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.5,
    },
    {
      url: `${base}/disclaimer`,
      lastModified: new Date("2026-10-03T00:00:00Z"),
      changeFrequency: "yearly",
      priority: 0.5,
    },
    {
      url: `${base}/sources`,
      lastModified: new Date("2026-10-03T00:00:00Z"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
  ];
}
